[tool.poetry]
name = "pythonbaseapi"
version = "0.1.0"
description = "Python API base image"
authors = ["Lounès ACHAB <lounes.achab@gmail.com>"]
license = "GNU General Public License v3.0"

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = "^0.15.0"
gunicorn = "^20.1.0"
uvloop = "^0.16.0"
httptools = "^0.3.0"
fastapi = "^0.68.1"


[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pre-commit = "^2.9.3"
flake8 = "^3.8.4"
mypy = "^0.790"
vulture = "^2.1"
bandit = "^1.6.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
